<a href="https://colab.research.google.com/github/duytrung/QuanLyTuyenSinh/blob/main/NumPy_arrays_demo_part_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy arrays methods


## 🛠️ Import NumPy
Before using NumPy, you need to import it

In [ ]:
import numpy as np

## 📃 Introduction

NumPy arrays are really powerfull tool. So they have a lot of useful methods included to make different useful calculations and even more.

Let's break it down!

## 🆘 Asking for help

NumPy can help you to remember how to use particular methods. If you forgot something you can use np.info() method giving a particular thing you forgot to get explanation how it works.

In [ ]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

## 🔢 Maths and statistics

Let's create an array we will use for calculations:

In [ ]:
arr = np.array([2, 1, 4, 5, 3, 10, 6, 8, 7, 9])

### 1️⃣ Sum and Size

In [ ]:
arr_size = arr.size

arr_size

10

**⚠️ Pay attention!**

As `.size` is not a method, but attribute, you don't need to put braces after this

In [ ]:
arr_sum = np.sum(arr)

arr_sum

55

If you need just to see the sum (or size) but not to use it in the future, you can just calculate it not storing a result in a variable

In [ ]:
np.sum(arr)

55

### 2️⃣ Max and Min

In [ ]:
max_val = np.max(arr)

max_val

10

In [ ]:
min_val = np.min(arr)

min_val

1

Or just calculating (as we discussed before)

In [ ]:
np.max(arr)

10

### 3️⃣ Max and Min indices

![execute a code cell](https://drive.google.com/uc?id=1Nb-mESpSpI7PyVKZzv2L7Hd5MbmfXFRo)

In [ ]:
max_index = np.argmax(arr)
max_index

5

In [ ]:
min_index = np.argmin(arr)
min_index

1

... or without storing

In [ ]:
np.max(arr)

10

### 4️⃣ Mean (average value) and Median

In [ ]:
mean = np.mean(arr)
mean

5.5

In [ ]:
median = np.median(arr)
median

5.5

### 📶 Sorting NumPy arrays

In [ ]:
sorted_arr = np.sort(arr)
sorted_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**⚠️ Pay attention!**

The np.sort() methods returns sorted array but does not change the source array.

You can check it trying to show the source array, it is still not sorted.

In [ ]:
arr

array([ 2,  1,  4,  5,  3, 10,  6,  8,  7,  9])

But the variables storing the result of the np.sort() contains the sorted version of the source array.

In [ ]:
sorted_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Conclusion

You got familiar with the most basic but useful methods of NumPy arrays.

You're great!🎉

So, it's time to go back to the presentation 😉