<a href="https://colab.research.google.com/github/duytrung/QuanLyTuyenSinh/blob/main/NumPy_arrays_demo_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy arrays demo - part 1

## 🛠️ Import NumPy

Before using NumPy, you need to import it

In [ ]:
import numpy as np

## 🏗 Array creation


### 1️⃣ From basic Python List

Arrays can be created in a lot of different ways
For example, from basic Python list

In [2]:
# A basic Python list creation
L1 = [1, 2, 3]

# Creating a NumPy array from the created list
A1 = np.array(L1)

NameError: name 'np' is not defined

Let's check the result

In [ ]:
L1

In [ ]:
A1

You are able to make it even the following way:

In [ ]:
A2 = np.array([5, 4, 3, 2, 1])
A2

### 2️⃣ Using the method `.arange(start, stop, step)`

There are special methods in the numpy library that let you create an array with some generated numerical data.

The first of them is `np.arange(start, stop, step)`

This method returns an array of numbers from `start` (including) to `stop` (excluding) with a `step` size of step.

To make it easier to remember let's state that **arange** is a **array from range**

In [ ]:
# Creating an array of integers starting from 1,
# ending with 10 (excluding), with the step of 2
arr1 = np.arange(1, 10, 2)

# Show the value of the variable
arr1

In [ ]:
# Creating an array of integers starting from 5,
# ending with 10 (excluding), with the step of 1 (by default)
arr2 = np.arange(5, 10)

# Show the value of the variable
arr2

In [3]:
# Creating an array of the first 10 integers
arr3 = np.arange(10)

# Show the value of the variable
arr3

NameError: name 'np' is not defined

### 3️⃣ Using the method `.linspace(start, stop, num)`

You also can use the method `np.linspace(start, stop, num)`

This method returns an array of `num` numbers from `start` (including) to `stop` (including), with equal spacing between them.

To make it easier to remember let's state that **linspace** is a **linear space**

In [ ]:
# Creating an array of numbers starting from 1 (including),
# ending with 10 (including), containing 10 elements with the equal spacing
arr1 = np.linspace(1, 10, 10)

# Show the value of the variable
arr1

📌 Please note that linspace **generates an array of floating point numbers** always.

In [ ]:
# Creating an array of numbers starting from 1 (including),
# ending with 2 (including), containing 11 elements with the equal spacing
arr2 = np.linspace(1, 2, 11)

# Show the value of the variable
arr2

### 4️⃣ Array of .ones()/.zeros()

Using methods .ones() and .zeros() you can create an array that contains a given number of ones/zeros

In [ ]:
# Creating an array of zeros containing 10 elements
arr_zeros = np.zeros(10)

# Show the value of the variable
arr_zeros

In [ ]:
# Creating an array of ones containing 5 elements
arr_ones = np.ones(5)

# Show the value of the variable
arr_ones

### 5️⃣ Using `random.randint(low, high, length)`


This method returns an array of `length` integers that have random values from `low` (including) to `high` (excluding).



In [ ]:
low = 5
high = 15
length = 10

# Creating an array of length random integers between low (including) and high (excluding)
randint_arr = np.random.randint (low, high, length)

# Show the value of the variable
randint_arr

### 6️⃣ Using `.random.random(length)`

This method returns an array of `length` float numbers in the range from 0 (inclusive) to 1 (exclusive).

In [ ]:
length = 10

# Creating an array of length random float numbers between 0 (including) and 1 (excluding)
random_arr = np.random.random(length)

# Show the value of the variable
random_arr

## 🎯 Accessing array elements


### 1️⃣ Accessing by index

You can access array element the same way you did with regular Python Lists using indices.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

arr[0]

1

In [ ]:
arr[1]

2

In [ ]:
arr[2]

3

### 2️⃣ Accessing by index

It means that you're able to iterate arrays as well.

In [ ]:
for i in arr:
  print(i)

1
2
3
4
5


### 3️⃣ Slicing

As accessing by indices works well, it would be reasonable to assume that slicing works too. And that's true

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr[1:4]

array([2, 3, 4])

In [ ]:
arr[2:]

array([3, 4, 5])

In [ ]:
arr[::-1]

array([5, 4, 3, 2, 1])

## Conclusion

You got familiar with the various ways of NumPy arrays creation.

You're great!🎉

So, it's time to go back to the presentation 😉