<a href="https://colab.research.google.com/github/duytrung/QuanLyTuyenSinh/blob/main/NumPy_arrays_demo_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arithmetics on NumPy arrays


## 🛠️ Import NumPy
Before using NumPy, you need to import it

In [ ]:
import numpy as np

## 🔢 Arithmetics


One of the most convenient features of arrays in NumPy is the ability to perform arithmetic operations on them. Let's see how it works.

### 1️⃣ With a scalar (single number)

Let's create an array of 5 random integers before

In [ ]:
arr = np.random.randint(1, 10, 5)

arr

array([3, 2, 9, 2, 3])

Then let's try to perform some arithmetics with the created array and a scalar value.

In [ ]:
arr2 = arr + 1

arr2

array([ 4,  3, 10,  3,  4])

In [ ]:
arr2 = arr * 10

arr2

array([30, 20, 90, 20, 30])

In [ ]:
arr2 = arr % 2

arr2

array([1, 0, 1, 0, 1])

In [ ]:
arr2 = arr ** 2

arr2

array([ 9,  4, 81,  4,  9])

### 2️⃣ With another array

You can perform mathematics even using 2 different arrays, not only array and a scalar value

Let's create 2 arrays

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

Then try to perform some calculations with them

In [ ]:
res_arr = arr1 + arr2

res_arr

array([5, 7, 9])

In [ ]:
res_arr = arr1 * arr2

res_arr

array([ 4, 10, 18])

... or even this

In [ ]:
res_arr = (arr1 + arr2 * 2) / np.array([7, 8, 9])

res_arr

array([1.28571429, 1.5       , 1.66666667])

### ⚠️ Pay attention

Operations with arrays of different lengths are not allowed.

This won't work!

In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6])

arr3 = arr1 + arr2

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## Conclusion

You got familiar with arithmetic operations on NumPy arrays.

You're great!🎉

⚠️ Please, do not forget, that operations with arrays of different length is impossible.

So, it's time to go back to the presentation 😉